version: "3.8"

services:

  nginx:
    build: "./nginx"
    container_name: "nginx"
    ports:
      - 3000:3000
#    networks:
#      - app
    depends_on:
      - node


  node:
    build: "./node"
    container_name: "node"
    #ports:
    #  - 3000:3000
